In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from m5py import M5Prime, export_text_m5

In [2]:
df = pd.read_excel('Gadarwara_Q.xlsx')
df

,Dates,Year,Month,Day,RF_1,RF_2,RF_3,RF_3(t-1),RF_3(t-2),RF_4,...,T12 min,T13 min,T12 avg,T12 avg(t-1),T13 avg,T13 avg(t-1),Baseflow,Unnamed: 42,Grid Point,weights
0,1977-06-01,1977,6,1,0.0,0.0,0.0,0.0,0.0,0.0,...,26.1,26.1,32.35,32.35,32.60,32.65,0.80,NaN,RF_1,0.013302
1,1977-06-02,1977,6,2,0.0,0.0,0.0,0.0,0.0,0.0,...,26.2,26.2,32.35,32.50,32.65,32.90,0.80,NaN,RF_2,0.010567
2,1977-06-03,1977,6,3,0.0,0.0,0.0,0.0,0.0,0.0,...,25.9,26.1,32.50,33.00,32.90,33.55,0.79,NaN,RF_3,0.086394
3,1977-06-04,1977,6,4,0.0,0.0,0.0,0.0,0.0,0.0,...,26.3,26.7,33.00,33.35,33.55,33.85,0.79,NaN,RF_4,0.273084
4,1977-06-05,1977,6,5,0.0,0.0,0.0,0.0,0.0,0.0,...,26.4,26.7,33.35,33.00,33.85,33.55,0.79,NaN,RF_5,0.104194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15701,2020-05-27,2020,5,27,0.0,0.0,0.0,0.0,0.0,0.0,...,27.1,27.2,34.45,34.50,35.10,34.90,0.08,NaN,NaN,NaN
15702,2020-05-28,2020,5,28,0.0,0.0,0.0,0.0,0.0,0.0,...,27.1,27.1,34.50,33.65,34.90,34.45,0.07,NaN,NaN,NaN
15703,2020-05-29,2020,5,29,0.0,0.0,0.0,0.0,0.0,0.0,...,27.3,27.5,33.65,33.50,34.45,33.55,0.05,NaN,NaN,NaN
15704,2020-05-30,2020,5,30,1.1,0.3,0.0,0.0,0.0,0.3,...,27.0,26.4,33.50,33.45,33.55,33.85,0.05,NaN,NaN,NaN
15705,2020-05-31,2020,5,31,0.0,0.0,0.0,0.0,0.0,0.0,...,26.6,26.8,33.45,33.50,33.85,33.50,0.05,NaN,NaN,NaN

In [3]:
part1 = df.drop(df.index[9496:15706])
part2 = df.drop(df.index[0:9496])
print(part1.shape, part2.shape)

(9496, 45) (6210, 45)

In [4]:
part1

,Dates,Year,Month,Day,RF_1,RF_2,RF_3,RF_3(t-1),RF_3(t-2),RF_4,...,T12 min,T13 min,T12 avg,T12 avg(t-1),T13 avg,T13 avg(t-1),Baseflow,Unnamed: 42,Grid Point,weights
0,1977-06-01,1977,6,1,0.0,0.0,0.0,0.0,0.0,0.0,...,26.1,26.1,32.35,32.35,32.60,32.65,0.80,NaN,RF_1,0.013302
1,1977-06-02,1977,6,2,0.0,0.0,0.0,0.0,0.0,0.0,...,26.2,26.2,32.35,32.50,32.65,32.90,0.80,NaN,RF_2,0.010567
2,1977-06-03,1977,6,3,0.0,0.0,0.0,0.0,0.0,0.0,...,25.9,26.1,32.50,33.00,32.90,33.55,0.79,NaN,RF_3,0.086394
3,1977-06-04,1977,6,4,0.0,0.0,0.0,0.0,0.0,0.0,...,26.3,26.7,33.00,33.35,33.55,33.85,0.79,NaN,RF_4,0.273084
4,1977-06-05,1977,6,5,0.0,0.0,0.0,0.0,0.0,0.0,...,26.4,26.7,33.35,33.00,33.85,33.55,0.79,NaN,RF_5,0.104194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9491,2003-05-27,2003,5,27,0.0,0.0,0.0,0.0,0.1,0.0,...,26.6,26.6,32.85,32.25,33.15,32.65,0.29,NaN,NaN,NaN
9492,2003-05-28,2003,5,28,0.0,0.0,0.0,0.0,0.0,0.0,...,25.9,26.3,32.25,32.70,32.65,32.90,0.28,NaN,NaN,NaN
9493,2003-05-29,2003,5,29,0.0,0.0,0.0,0.0,0.0,0.0,...,26.4,26.3,32.70,33.50,32.90,33.55,0.28,NaN,NaN,NaN
9494,2003-05-30,2003,5,30,0.0,0.0,0.0,0.0,0.0,0.0,...,26.4,26.3,33.50,33.75,33.55,34.05,0.27,NaN,NaN,NaN
9495,2003-05-31,2003,5,31,0.0,0.0,0.0,0.0,0.0,0.0,...,26.0,26.3,33.75,33.85,34.05,34.80,0.27,NaN,NaN,NaN

In [5]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [6]:
X = part1[['RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.36247615245712284
R2_score2 =  0.35509379745622527
R2_score3 =  -0.13967104165646527
R2_score4 =  -0.22609301506401058

In [7]:
X = part1[['Q(t-1)', 'Q(t-2)', 'Q(t-3)','RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)', 'Q(t-3)','RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.4429547443321905
R2_score2 =  0.3597852883562397
R2_score3 =  -0.3225024426391556
R2_score4 =  0.12316968069209255

In [8]:
X = part1[['Q(t-1)', 'Q(t-2)', 'Q(t-3)', 'Q(t-4)', 'RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'T13 avg', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)', 'Q(t-3)', 'Q(t-4)', 'RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'T13 avg', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.4675341362977511
R2_score2 =  0.47436925160869614
R2_score3 =  -0.1097921035173357
R2_score4 =  0.31890305424715415

In [9]:
X = part1[['Q(t-1)', 'Q(t-2)', 'RF_4(t-1)', 'RF_8(t-1)',  'T13 avg', 'T12 avg','Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)','RF_4(t-1)', 'RF_8(t-1)',  'T13 avg', 'T12 avg', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.47011012542160724
R2_score2 =  0.4659653267334458
R2_score3 =  0.2862072524614244
R2_score4 =  0.12987777942265244

In [10]:
X = part1[['Q(t-1)', 'Q(t-2)', 'Q(t-3)', 'RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'T12 avg', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)', 'Q(t-3)', 'RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'T12 avg', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.44717607492697664
R2_score2 =  0.39141082383821657
R2_score3 =  -2.2602474664357035
R2_score4 =  0.12476567506715341

In [11]:
X = part1[['Q(t-1)', 'Q(t-2)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'T12 avg', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'T12 avg', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.43605274534034644
R2_score2 =  0.44604619930141154
R2_score3 =  -0.9359246231236293
R2_score4 =  0.04322973693080845

In [12]:
X = part1[['Q(t-1)', 'Q(t-2)', 'RF_8(t-1)', 'RF_4(t-1)', 'T12 avg', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)', 'RF_8(t-1)', 'RF_4(t-1)', 'T12 avg', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.45551629222527257
R2_score2 =  0.45852592386556235
R2_score3 =  -0.649466047778573
R2_score4 =  0.19623672487067745

In [13]:
X = part1[['Q(t-1)', 'Q(t-2)',  'RF_8(t-1)', 'RF_6(t-1)', 't-1', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)',  'RF_8(t-1)', 'RF_6(t-1)', 't-1', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.4572405511615225
R2_score2 =  0.4798465013912979
R2_score3 =  0.23937930553645348
R2_score4 =  0.268856121153876

In [14]:
X = part1[['Q(t-1)', 'Q(t-2)', 'Q(t-3)','RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)', 'Q(t-3)', 'RF_5(t-1)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.366313764515965
R2_score2 =  0.4181835658578543
R2_score3 =  -2.2978634215093314
R2_score4 =  0.0841526237614455

In [15]:
X = part1[['Q(t-1)', 'Q(t-2)', 'RF_3(t-1)','RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)','RF_3(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.3834294331178588
R2_score2 =  0.34809454880130475
R2_score3 =  -3.3619673381223683
R2_score4 =  -0.012431541549386305

In [16]:
X = part1[['Q(t-1)', 'Q(t-2)', 'RF_4(t-1)','RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)','RF_4(t-1)', 'RF_8(t-1)', 'RF_6(t-1)', 'Baseflow']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.4151462716435588
R2_score2 =  0.42280958079626396
R2_score3 =  -2.1520996123635556
R2_score4 =  0.06159254942394543

In [17]:
X = part1[['Q(t-1)', 'Q(t-2)', 'Baseflow', 'RF_8(t-1)', 't-1']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)','Baseflow', 'RF_8(t-1)', 't-1']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.4693510967065493
R2_score2 =  0.4878620837633998
R2_score3 =  0.11659497038628752
R2_score4 =  0.19129106090243375

In [18]:
X = part1[['Q(t-1)', 'Q(t-2)', 'Baseflow', 'RF_8(t-1)', 't-1', 'T12 avg']].values
Y = part1['Q'].values
regr_1 = M5Prime(use_smoothing=True, use_pruning=True)
regr_2 = M5Prime(use_smoothing=True, use_pruning=False)
regr_3 = M5Prime(use_smoothing=False, use_pruning=True)
regr_4 = M5Prime(use_smoothing=False, use_pruning=False)
regr_1_label = "Tree 1"
regr_2_label = "Tree 2"
regr_3_label = "Tree 3"
regr_4_label = "Tree 4"

regr_1.fit(X, Y)
regr_2.fit(X, Y)
regr_3.fit(X, Y)
regr_4.fit(X, Y)

X_test = part2[['Q(t-1)', 'Q(t-2)','Baseflow', 'RF_8(t-1)', 't-1', 'T12 avg']].values
Y_test = part2['Q'].values
Y_pred1 = regr_1.predict(X_test)
Y_pred2 = regr_2.predict(X_test)
Y_pred3 = regr_3.predict(X_test)
Y_pred4 = regr_4.predict(X_test)

R2_score1 = r2_score(Y_test, Y_pred1)
R2_score2 = r2_score(Y_test, Y_pred2)
R2_score3 = r2_score(Y_test, Y_pred3)
R2_score4 = r2_score(Y_test, Y_pred4)

print("R2_score1 = ", R2_score1)
print("R2_score2 = ", R2_score2)
print("R2_score3 = ", R2_score3)
print("R2_score4 = ", R2_score4)

R2_score1 =  0.48980422736951035
R2_score2 =  0.49864319192089035
R2_score3 =  0.20379818280348827
R2_score4 =  0.09087911662678794